# Generated by Django 4.1.2 on 2022-11-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asiento',
            old_name='Fila',
            new_name='columna',
        ),
        migrations.AddField(
            model_name='asiento',
            name='fila',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
