# Generated by Django 4.1.2 on 2022-11-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_fila_asiento_columna_asiento_fila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asiento',
            name='Asiento',
            field=models.CharField(max_length=10),
        ),
    ]
